### ISSUE TITLE
Manx plugin, Invisible text, white on white

### ISSUE THREAD

**Issue by clr2of8** [mitre/manx#19]
The text in the Manx drop down menus is not visible because it is white on white.

![image](https://user-images.githubusercontent.com/22311332/93690017-3d11cc80-fa91-11ea-8dfe-807849cde83a.png)

**Comment by wbooth** [comment]
thanks, fixed here: https://github.com/mitre/manx/pull/22

**Comment by FlavienMtd** [comment]
Hi, I'm using the version 2.8.1-caf7c8403a9385500097bf8af870e206 and still have the same issue
